---
kind: pipeline

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: always
  image: golang:1.16
  commands:
  - go build -v -ldflags '-X main.version=${DRONE_TAG##v} -X main.build=1' -a -o release/linux/amd64/drone-discord
  environment:
    CGO_ENABLED: 0

- name: executable
  pull: always
  image: golang:1.16
  commands:
  - ./release/linux/amd64/drone-discord --help

- name: publish
  pull: always
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: theglow666/drone-discord
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/pull/**
  - refs/tags/**

